# apiVersion: 1
# groups:
#   - orgId: 1
#     name: dudu
#     folder: Demo
#     interval: 10s
#     rules:
#       - uid: edk6o4wdavpc0b
#         title: Latency for Recommendation Service
#         condition: F
#         data:
#           - refId: Latency
#             relativeTimeRange:
#               from: 900
#               to: 0
#             datasourceUid: webstore-metrics
#             model:
#               datasource:
#                 type: prometheus
#                 uid: webstore-metrics
#               editorMode: builder
#               exemplar: true
#               expr: histogram_quantile(0.50, sum(rate(duration_milliseconds_bucket{service_name="recommendationservice"}[$__rate_interval])) by (le))
#               instant: false
#               interval: ""
#               intervalMs: 15000
#               legendFormat: quantile50
#               maxDataPoints: 43200
#               range: true
#               refId: Latency
#           - refId: E
#             relativeTimeRange:
#               from: 600
#               to: 0
#             datasourceUid: __expr__
#             model:
#               conditions:
#                 - evaluator:
#                     params: []
#                     type: gt
#                   operator:
#                     type: and
#                   query:
#                     params:
#                       - E
#                   reducer:
#                     params: []
#                     type: last
#                   type: query
#               datasource:
#                 type: __expr__
#                 uid: __expr__
#               expression: Latency
#               intervalMs: 1000
#               maxDataPoints: 43200
#               reducer: max
#               refId: E
#               type: reduce
#           - refId: F
#             relativeTimeRange:
#               from: 600
#               to: 0
#             datasourceUid: __expr__
#             model:
#               conditions:
#                 - evaluator:
#                     params:
#                       - 2
#                     type: gt
#                   operator:
#                     type: and
#                   query:
#                     params:
#                       - F
#                   reducer:
#                     params: []
#                     type: last
#                   type: query
#               datasource:
#                 type: __expr__
#                 uid: __expr__
#               expression: E
#               intervalMs: 1000
#               maxDataPoints: 43200
#               refId: F
#               type: threshold
#         dashboardUid: W2gX2zHVk
#         panelId: 2
#         noDataState: NoData
#         execErrState: Error
#         for: 0s
#         annotations:
#           __dashboardUid__: W2gX2zHVk
#           __panelId__: "2"
#           summary: serious issue
#         labels: {}
#         isPaused: false
