global:
  resolve_timeout: 1m
  slack_api_url: "<slack webhook url>" # See here: https://api.slack.com/messaging/webhooks

route:
  receiver: "slack-notifications"
  routes:
    - receiver: "slack-notifications"
      continue: true
    - receiver: "api-notifications"

receivers:
  - name: "api-notifications"
    webhook_configs:
      - url: "http://host.docker.internal:3000/webhooks/alertmanager"
        send_resolved: true
        http_config:
          authorization:
            type: Bearer
            credentials: "091aab16-6912-451c-bea0-60e7167f89aa"
  - name: "slack-notifications"
    slack_configs:
      - channel: "#critical-alerts"
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          *Description:* {{ .Annotations.description }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
