# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
#  exporters:
#    otlphttp/example:
#      endpoint: <your-endpoint-url>
#
#  service:
#    pipelines:
#      traces:
#        exporters: [spanmetrics, otlphttp/example]

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  coralogix:
    # The Coralogix traces ingress endpoint
    traces:
      endpoint: "ingress.${env:CORALOGIX_DOMAIN}:443"
    metrics:
      endpoint: "ingress.${env:CORALOGIX_DOMAIN}:443"
    logs:
      endpoint: "ingress.${env:CORALOGIX_DOMAIN}:443"
    # Your Coralogix private key is sensitive
    private_key: "${env:CORALOGIX_PRIVATE_KEY}"

    # AppNameSubSystem values.
    # The first non-empty resource attribute is used.
    # application_name_attributes:
    #   - "service.namespace"
    #   - "k8s.namespace.name"
    # subsystem_name_attributes:
    #   - "service.name"
    #   - "k8s.deployment.name"
    #   - "k8s.statefulset.name"
    #   - "k8s.daemonset.name"
    #   - "k8s.cronjob.name"
    #   - "k8s.job.name"
    #   - "k8s.container.name"
    # It is required that logs, metrics and traces emitted by this exporter
    # are tagged in Coralogix
    # with the default application and subsystem constants.
    # Traces, Metrics and Logs emitted by this OpenTelemetry exporter
    # are tagged in Coralogix with the default application and subsystem constants.
    application_name: "${env:CORALOGIX_APP_NAME}"
    subsystem_name: "${env:CORALOGIX_SUBSYS_NAME}"

    # (Optional) Timeout is the timeout for every attempt to send data to the backend.
    timeout: 30s

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [opensearch, debug, coralogix, loki] # Note: need to change CORALOGIX_PRIVATE_KEY in the .env in order to export to Coralogix
